version: '2'

services:
    python:
        build:
            context: .
            dockerfile: app.dockerfile
        environment:
            API_ID: 1508a9a4840a5574c822d70ca2132032
            API_TOKEN: 3b719353762f7ddfc080e13556d248e8d8af1a63590b6d17738e4f57ac18a5d1
            API_VERSION: /api/v1
            OPENWEATHER_API_URL: http://api.openweathermap.org/data/2.5/weather
            PROJECT_NAME: WeatherAPI
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_EXPIRATION_TIME: 120
            VERSION: 0.1
        ports:
            - 3000:8000
        networks:
            - wheaterapp
    redis:
        image: redis
        networks:
            - wheaterapp
networks:
    wheaterapp:
        driver: bridge
