version: '2'

services:
    python:
        build: 
            context: .
            dockerfile: app.dockerfile
        ports: 
            - 3000:8080
        networks: 
            - wheaterapp
    redis:
        image: redis
        networks: 
            - wheaterapp
networks:
    wheaterapp:
        driver: bridge